//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XepLichGiangVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LichDay
    {
        [Key]
        public int MaLich { get; set; }
        public string MaLHP { get; set; }
        public Nullable<int> Thu { get; set; }
        public Nullable<int> TietBatDau { get; set; }
        public Nullable<int> TietKetThuc { get; set; }
        public Nullable<int> TuanBatDau { get; set; }
        public Nullable<int> TuanKetThuc { get; set; }
        public string MaPhong { get; set; }
    
        public virtual LopHocPhan LopHocPhan { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
    }
}
