//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XepLichGiangVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LopHocPhan
    {
        [Key]
        public string MaLHP { get; set; }
        public string TenMH { get; set; }
        public double SoTinChi { get; set; }
        public int SoLuongSV { get; set; }
        public int SoTietMoiTuan { get; set; }
        public string MaGV { get; set; }

        public virtual GiangVien GiangVien { get; set; }
        public virtual ICollection<LichDay> LichDays { get; set; }
    }
}
