//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XepLichGiangVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class TaiKhoan
    {
        [Key]
        public string MaTaiKhoan { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string MaGV { get; set; }
        public int MaVaiTro { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
